### ISSUE TITLE
CicrleCI not working

### ISSUE THREAD

**Issue by mkopylec** [kt3k/coveralls-gradle-plugin#55]
I have a project which is build by Gradle.
In circle.yml I have:
```
test:
  post:
    - ./gradlew jacocoTestReport coveralls`
```
The coverage data is not send to Coveralls after successful build.
Instead the `no available CI service` message is displayed.

**Comment by ObjectiveTruth** [comment]
I'm hoping we have the same issue, and its extremely **obvious/cryptic** on how to solve it. 

##### You need your `repo` token in the environment under COVERALLS_REPO_TOKEN

If you go to your Repo page in Coveralls, there are instructions for `Ruby`. Of course my eyes darted since it says if you're not using `Ruby` to click the documentation.

If you look through the example code, the repo code is inserted there.

--------
If that doesn't work try the following to debug

Try passing in the environmental variables manually to `./gradlew coveralls`

example: `CI=true CIRCLECI=true COVERALLS_REPO_TOKEN=123 ./gradlew coveralls`

Should at least blow up, instead of saying `no available CI service`

Good luck! :stars:

**Comment by mkopylec** [comment]
Hi, I'm not using coveralls anymore, so I won't check your solution, but thanks anyway.
